<a href="https://colab.research.google.com/github/vignanbandi/padhai_data_science/blob/master/numpy_problems.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
cric_data = np.loadtxt('cric_data-200320-181217.tsv', skiprows=1, usecols=(1,2,3))

# Question -1
# Find Mean, Median, IQR for Sachin, Rahul, India

## Calculate Mean

In [0]:
# axis = 0 calculates along columns i.e for each cloumn calculates the mean for row
# (typical Y axis or columns avg in 2d array)
cric_data_means = np.mean(cric_data, axis=0)
sachin_mean, rahul_mean, india_mean = cric_data_means
print(sachin_mean, rahul_mean, india_mean)

39.87555555555556 32.062222222222225 220.79555555555555


## Calculate Median

In [0]:
cric_data_median = np.median(cric_data, axis=0)
sachin_median, rahul_median, india_median = cric_data_median
print(sachin_median, rahul_median, india_median)

27.0 22.0 216.0


## Calculate IQR

In [25]:
cric_iqrs = np.percentile(cric_data, (25, 75), axis=0)
print(cric_iqrs)
cric_iqrs[1] - cric_iqrs[0]

[[  6.   7. 175.]
 [ 63.  53. 273.]]


array([57., 46., 98.])

# Q2 - Find histogram of sachin's score with 10 bins


In [0]:
# while indexing 2d array first index is row, second index is column
np.histogram(cric_data[:, 0], bins=10)

(array([99, 36, 28, 16, 11, 17,  8,  8,  1,  1]),
 array([  0. ,  18.6,  37.2,  55.8,  74.4,  93. , 111.6, 130.2, 148.8,
        167.4, 186. ]))

# Q3 - Find the mean of sachin's score grouped by 25 matches

In [28]:
len( cric_data[:, 0])/25

9.0

In [31]:
# Ineffient way of doing this
sachins_scores = cric_data[:, 0]
lower_index = 0
for group in range(1, int(len(cric_data)/25 + 1)):
    print(f"Sachins mean in {group} 25 matches", np.mean(sachins_scores[lower_index: group * 25]))
    lower_index = group * 25

Sachins mean in 1 25 matches 33.96
Sachins mean in 2 25 matches 49.4
Sachins mean in 3 25 matches 38.48
Sachins mean in 4 25 matches 40.16
Sachins mean in 5 25 matches 39.36
Sachins mean in 6 25 matches 38.2
Sachins mean in 7 25 matches 44.6
Sachins mean in 8 25 matches 39.52
Sachins mean in 9 25 matches 35.2


In [35]:
# Efficient numpy way
sachins_scores.shape
grouped_scores = sachins_scores.reshape(9, 25)
np.mean(grouped_scores, axis=1)


array([33.96, 49.4 , 38.48, 40.16, 39.36, 38.2 , 44.6 , 39.52, 35.2 ])